### ISSUE TITLE
report age of oldest unread email

### ISSUE THREAD

**Issue by raboof** [bt909/imap-mailstat-exporter#21]
Thanks for this incredibly useful exporter.

As a feature request, I think it would be very useful to have a way to export the timestamp of the oldest unread email in a mailbox. That might make it easier to detect when mailboxes aren't read without having to actually manually open them.

**Comment by bt909** [comment]
Hello @raboof,

thanks for your issue/feature request. It sounds like a very useful feature and I would like to try to add it in one of the next versions.

**Comment by raboof** [comment]
Yes, that works fine and looks incredibly useful! Already incorporated in our dashboard :smile: 

I could imagine for some people it would be more convenient if this setting could be set per mailbox in the configuration file, but for me this is fine, I want it for all of them :)

**Comment by raboof** [comment]
(I should really finish https://github.com/NixOS/nixpkgs/pull/243338 some day ;) - but already using it in https://codeberg.org/eicas/server-config/src/branch/main/monitoring.nix#L40)

**Comment by bt909** [comment]
Oh wow, nice to see where it is used. I started to create releases, or want to create releases, so that you not need to update if i just updated my readme. There will be latest amd64 Docker Images available with digest, but binaries will be available in a released manner and I want to have released Docker Images as well, so if you build nix packages (very nice) you can maybe use releases, so that you not have to update often because I play around...

**Comment by raboof** [comment]
Nice! Updated https://github.com/NixOS/nixpkgs/pull/243338 to build from the release tag. Still need to 'nixify' the configuration though ;)

**Comment by raboof** [comment]
> Nice! Updated [NixOS/nixpkgs#243338](https://github.com/NixOS/nixpkgs/pull/243338) to build from the release tag. Still need to 'nixify' the configuration though ;)

(fyi this is now ready for review and inclusion in nixpkgs :crossed_fingers: )
